title: Hoang Tran
description:  Data Scientist/Machine Learning Engineer
url: https://hoangftran.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
